@php($prefix = 'stalls.'.$i.'.foods.'.$j)
@php($input = 'stalls['.$i.'][foods]['.$j.']')
<section class="ai-food card card-body my-3">
<div class="ai-food-top"><div>
@if(!empty($food['image_path']))<img class="ai-food-photo" src="{{ route('admin.ai-import.image',[$proposal,$i,$j]) }}" alt="Draft photo for {{ $food['name'] }}" data-upload-preview>@else<img class="ai-food-photo" src="{{ asset('images/food-placeholder.svg') }}" alt="No confirmed food photo" data-upload-preview>@endif
<label class="form-label mt-2">Upload / replace photo<input type="file" name="{{ $input }}[image]" class="form-control" accept="image/jpeg,image/png,image/webp" data-image-input></label>
<label class="ai-check"><input type="checkbox" class="form-check-input" name="{{ $input }}[remove_image]" value="1"> Remove photo</label>
</div><div class="min-w-0"><label class="ai-check"><input type="hidden" name="{{ $input }}[selected]" value="0"><input type="checkbox" class="form-check-input" name="{{ $input }}[selected]" value="1" @checked(old($prefix.'.selected',$food['selected'] ?? false)) data-select-food> Include Food</label><h4 class="h5">{{ $food['name'] }}</h4><p class="small">Parent Stall: {{ $stall['name'] }}</p><span class="badge {{ $food['missing'] ? 'text-bg-warning' : 'text-bg-success' }}">{{ $food['missing'] ? 'Needs information' : 'Complete' }}</span>@if($food['missing'])<p class="small mt-2">Missing: {{ implode(' · ',$food['missing']) }}</p>@endif
<label class="form-label w-100">Food name<input class="form-control" name="{{ $input }}[name]" value="{{ old($prefix.'.name',$food['name']) }}"></label><label class="form-label w-100">Category<select name="{{ $input }}[category]" class="form-select"><option value="">Choose category</option>@foreach($review['categories'] as $category)<option @selected(old($prefix.'.category',$food['category'])===$category)>{{ $category }}</option>@endforeach</select></label>
</div></div>
<label class="form-label">Description<textarea class="form-control" name="{{ $input }}[description]" rows="2">{{ old($prefix.'.description',$food['description'] ?? '') }}</textarea></label>
<div class="row g-2">@foreach(['price_min'=>'Price from (RM)','price_max'=>'Price to (RM)','unit'=>'Serving / unit','price_checked_at'=>'Price checked date'] as $key=>$label)<div class="col-sm-6"><label class="form-label w-100">{{ $label }}<input class="form-control" name="{{ $input }}[{{ $key }}]" type="{{ str_starts_with($key,'price_') && $key !== 'price_checked_at' ? 'number' : ($key==='price_checked_at' ? 'date' : 'text') }}" @if(in_array($key,['price_min','price_max'])) step="0.01" min="0.01" @endif value="{{ old($prefix.'.'.$key,$food[$key] ?? '') }}"></label></div>@endforeach</div>
<input type="hidden" name="{{ $input }}[currency]" value="MYR"><p class="small">Currency: MYR. For a single price enter the same amount twice. Unknown prices stay blank; no averages are inferred.</p>
@if(!empty($food['price_display']))<p class="small">Source price wording: <strong>{{ $food['price_display'] }}</strong>. Confirm the serving or bundle size above; this is not necessarily a per-item price.</p>@endif
<label class="form-label">Link existing Food (no fields will be overwritten)<select class="form-select" name="{{ $input }}[matched_food_id]" data-existing-food><option value="">Create new inactive Food</option>@foreach($review['existingStalls'] as $existingStall)@foreach($existingStall->foods as $existingFood)<option value="{{ $existingFood->id }}" data-stall="{{ $existingStall->id }}" @selected(old($prefix.'.matched_food_id',$food['matched_food_id'] ?? null)==$existingFood->id)>{{ $existingStall->name }} · {{ $existingFood->name }}</option>@endforeach @endforeach</select></label>
@if($food['duplicates'])<p class="alert alert-warning small">Possible duplicate Food. Link the matching Food or deselect it.</p>@endif
<details><summary>Source, evidence & candidate photos</summary><p class="ai-evidence small">{{ $food['evidence_text'] ?? 'No evidence available.' }}</p>@if(!empty($food['source_url']))<a href="{{ $food['source_url'] }}" target="_blank" rel="noopener noreferrer">Open evidence source</a>@endif
<p class="small mt-2">Source images are not automatically food photos. Confirm relevance and permission. Video covers are not food photo candidates.</p>
<div class="ai-photo-options">@foreach($review['sources'] as $sourceIndex=>$source)@foreach($source['images'] ?? [] as $candidateIndex=>$candidate)<label><input type="radio" name="{{ $input }}[candidate_image]" value="{{ $candidate['url'] }}"><span>{{ $candidate['caption'] ?: 'Source image' }}</span><img hidden class="ai-source-image" alt="Source candidate; relevance needs confirmation"><button type="button" class="btn btn-outline-secondary" data-candidate-preview="{{ route('admin.ai-import.candidate-image',[$proposal,$sourceIndex,$candidateIndex]) }}">Preview candidate</button><a href="{{ $candidate['url'] }}" target="_blank" rel="noopener noreferrer">Preview source image</a></label>@endforeach @endforeach</div></details>
<label class="ai-check"><input type="hidden" name="{{ $input }}[photo_confirmed]" value="0"><input class="form-check-input" type="checkbox" name="{{ $input }}[photo_confirmed]" value="1" @checked(old($prefix.'.photo_confirmed',$food['photo_confirmed'] ?? false))> I confirm this photo shows this Food and I have permission to use it.</label>
</section>
