@extends('layouts.app')
@section('title', 'Review Import | NightBite')
@section('content')<div class="ai-import">
@include('admin.ai-import._header', ['heading' => 'Review Import', 'stage' => $proposal->status === 'imported' ? 3 : 2])
<div class="card market-card card-body mb-3 position-sticky top-0 z-2" aria-label="Current draft"><strong>Draft #{{ $proposal->id }} · {{ $proposal->target_type === 'new_market' ? 'Create New Market' : 'Add to Existing Catalog' }}</strong><span>{{ $review['marketName'] }} @if($review['marketCity']) · {{ $review['marketCity'] }} @endif</span><span class="small text-secondary">Last saved: {{ $proposal->updated_at->format('d M Y, H:i') }}</span></div>
@foreach($review['repair_warnings'] ?? [] as $warning)<div class="alert alert-warning"><strong>Needs Repair:</strong> {{ $warning }} The remaining valid draft data is still available.</div>@endforeach
@if(!empty($review['_using_last_good']))<form method="POST" action="{{ route('admin.ai-import.restore',$proposal) }}" class="mb-3">@csrf<button class="btn btn-outline-market">Restore this last good version as the current draft</button></form>@endif
@if($proposal->status === 'imported')
<div class="alert alert-success">Imported. Refreshing this page does not import again. New records remain inactive until normal Admin activation.</div>
<a class="btn btn-market mb-3" href="{{ route('admin.ai-import.success',$proposal) }}">View import summary and skipped records</a>
<div class="d-flex flex-wrap gap-2">@foreach($review['import_result']['records'] as $record)<a class="btn btn-outline-market" href="{{ route(match($record['type']) { 'food'=>'admin.foods.show', 'market'=>'admin.night-markets.show', default=>'admin.stalls.show' },$record['id']) }}">{{ $record['name'] }}</a>@endforeach</div>
@else
<div class="alert alert-info">Review the Market → Stalls → Foods below. Only your selected, complete records will be imported. New records are inactive; existing records will not be overwritten. Confirm your review before creating records; no separate approval workflow follows.</div>
@if($review['marketIncomplete'])<div class="alert alert-warning" data-market-missing-alert><strong>Incomplete Market details:</strong> <span data-market-missing-text>{{ implode(' · ', $review['marketIncomplete']) }}</span>. This does not block an inactive import; complete and verify the details before making the Market public.</div>@endif
@foreach($review['market_conflicts'] ?? [] as $conflict)<div class="alert alert-warning" role="alert"><strong>Source conflict:</strong> {{ $conflict }}</div>@endforeach
<div class="ai-workspace"><aside class="ai-sources-panel" id="draft-sources">
<details class="card card-body" @if($errors->has('source')) open @endif><summary class="fw-bold">Sources &amp; additional analysis ({{ count($review['sources']) }})</summary>
<p class="small">Existing evidence and edits are retained. Analyse only additional sources or segments you need.</p>
<form method="POST" action="{{ route('admin.ai-import.analyse',$proposal) }}" enctype="multipart/form-data" data-ai-busy="Reading selected content and extracting draft items…">@csrf
@foreach($review['sources'] as $i => $source)<article class="card mb-3" data-source-card><div class="card-body"><h2 class="h6">{{ $source['title'] }}</h2><label class="ai-check"><input type="checkbox" name="source_ids[]" value="{{ $i }}" class="form-check-input" @checked(count($review['sources']) === 1)><span data-source-selection>{{ count($review['sources']) === 1 ? 'Selected' : 'Not selected' }}</span><span class="visually-hidden">: {{ $source['title'] }}</span></label><p class="small" role="status">{{ $source['status'] }}</p>@if(!empty($source['old_source']))<p class="alert alert-warning small">Old source: do not use it as proof of a currently operating Stall or current price without checking it again.</p>@endif @if(!empty($source['url']))<a href="{{ $source['url'] }}" target="_blank" rel="noopener noreferrer">Open Source</a>@else<span class="text-danger">Source URL needs repair</span>@endif
@if(!empty($source['thumbnail']))<img class="ai-source-image my-2" src="{{ $source['thumbnail'] }}" alt="Video cover (source preview only)" loading="lazy" referrerpolicy="no-referrer">@endif<p class="small text-secondary">{{ $source['publisher'] }} · {{ $source['published_at'] ?? 'Publication date unavailable' }}</p>@if(!empty($source['metadata_status']))<p class="small">{{ $source['metadata_status'] }}</p>@endif @if(($source['type'] ?? null)==='article' && !empty($source['description']))<label class="ai-check"><input class="form-check-input" type="checkbox" name="use_search_summary_ids[]" value="{{ $i }}"> If Retry cannot read the webpage, analyse its search summary as low-confidence fallback</label>@endif @if(!empty($source['low_confidence_fallback']))<p class="alert alert-warning small">Low-confidence search summary used. It is not the article body and needs independent confirmation.</p>@endif
@if(!empty($source['text']))<details class="mt-2"><summary>Read extracted evidence</summary><p class="ai-evidence">{{ $source['text'] }}</p></details>@endif</div></article>@endforeach
<label for="additional-url" class="form-label">Add another source URL</label><input type="url" name="url" id="additional-url" class="form-control mb-3" placeholder="https://…">
<details class="mb-3"><summary>Video segment (not the full video)</summary><p class="small mt-2" id="video-range-help">For video URLs, analyse one source and up to 180 seconds at a time. Default: the first 120 seconds, or the video end if earlier. Check the video length using Open Source. To analyse another segment, choose its range explicitly. Text and screenshots do not use this range.</p><div class="row g-2"><label class="col-sm-6" for="video-start">Start (seconds)<input id="video-start" name="video_start_seconds" type="number" min="0" max="43199" class="form-control" value="{{ old('video_start_seconds',0) }}" aria-describedby="video-range-help"></label><label class="col-sm-6" for="video-end">End (seconds)<input id="video-end" name="video_end_seconds" type="number" min="1" max="43200" class="form-control" value="{{ old('video_end_seconds',120) }}" aria-describedby="video-range-help"></label></div></details>
<details><summary>Provide text or screenshot instead</summary><label class="form-label mt-2" for="source-text">Text from the selected source</label><textarea class="form-control" id="source-text" name="text" rows="5" maxlength="30000"></textarea><label class="form-label mt-2" for="screenshot">Source screenshot (JPEG, PNG, WebP; 5 MB)</label><input class="form-control" type="file" name="screenshot" id="screenshot" accept="image/jpeg,image/png,image/webp"><p class="small">Select one source when supplying text/screenshots. A video timestamp is not an image file.</p></details>
<button type="submit" class="btn btn-market w-100 mt-3">Analyse &amp; Prepare Import</button><p class="small mt-2" role="status" data-busy-status>Only selected sources are analysed. Existing edits are retained; additional variants require review. Save any unsaved edits before analysing another source.</p></form></details></aside>
<section class="min-w-0"><h2 class="h4">{{ $review['marketName'] }} · {{ $review['marketCity'] }}, Selangor</h2><p>Check ownership and evidence. Missing information can remain in saved work. Uncheck incomplete items to import other complete items.</p>
<form method="POST" action="{{ route('admin.ai-import.complete',$proposal) }}" enctype="multipart/form-data" data-ai-busy="Saving your review and processing selected records…" data-review-editor data-source-count="{{ count($review['sources']) }}">@csrf<input type="hidden" name="revision" value="{{ $revision }}">
@foreach($review['sources'] as $sourceIndex=>$source)@if(!empty($source['old_source']))<input type="hidden" name="sources[{{ $sourceIndex }}][old_source_confirmed]" value="0"><label class="ai-check mb-2"><input class="form-check-input" type="checkbox" name="sources[{{ $sourceIndex }}][old_source_confirmed]" value="1" @checked($source['old_source_confirmed'] ?? false)> I checked this old source and explicitly allow its supported evidence in this draft.</label>@endif @endforeach
@if(!$review['context']['market_id'])<div class="card card-body mb-3"><h3 class="h5">Market identity</h3><input type="hidden" name="market[selected]" value="0"><label class="ai-check"><input type="checkbox" class="form-check-input" name="market[selected]" value="1" @checked(old('market.selected',$review['graph']['market']['selected'] ?? true))> Include this new inactive Market in the import</label>@foreach(['name'=>'Market name','address'=>'Address','city'=>'City'] as $key=>$label)<label class="form-label">{{ $label }}<input name="market[{{ $key }}]" class="form-control" value="{{ old('market.'.$key,$review['graph']['market'][$key] ?? '') }}"></label>@endforeach<label>Link an existing Market instead<select class="form-select" name="market[matched_night_market_id]"><option value="">Create a new inactive Market</option>@foreach($nightMarkets as $m)<option value="{{ $m->id }}" @selected(($review['graph']['market']['matched_night_market_id'] ?? null)==$m->id)>{{ $m->name }} · {{ $m->city }}</option>@endforeach</select></label><p class="small mt-2">Selangor only. A new Market may be imported as inactive while its address or operating days remain incomplete. Complete and verify those details before activation.</p></div>@endif
@if(!$review['context']['market_id'])
<p class="small">The name and city identify the Market you selected, not an AI verification. Check the location against the source before import. New Markets are always inactive.</p>
@foreach($review['market_sources'] ?? [] as $marketSource => $marketEvidence)<details class="mb-3"><summary>Market source evidence</summary><p class="ai-evidence">{{ $marketEvidence }}</p><a href="{{ $marketSource }}" target="_blank" rel="noopener noreferrer">Open Market Source</a></details>@endforeach
<details class="card card-body mb-3"><summary>Operating days & source evidence</summary><p class="small">Unknown days can remain unselected when importing an inactive Market. A source-supported day may be saved with unknown times; do not guess missing times.</p>
@foreach(\App\Models\MarketOperatingDay::DAYS as $dayIndex=>$day)
@php($schedule = collect($review['graph']['operating_days'])->firstWhere('day_of_week',$day))
<div class="border-bottom py-2"><input type="hidden" name="operating_days[{{ $dayIndex }}][day_of_week]" value="{{ $day }}"><input type="hidden" name="operating_days[{{ $dayIndex }}][selected]" value="0"><label class="ai-check"><input type="checkbox" class="form-check-input" name="operating_days[{{ $dayIndex }}][selected]" value="1" @checked(old('operating_days.'.$dayIndex.'.selected',(bool)$schedule))> {{ $day }}</label><div class="row g-2">@foreach(['opening_time'=>'Opens','closing_time'=>'Closes'] as $field=>$label)<label class="col-sm-6">{{ $label }}<input type="time" class="form-control" name="operating_days[{{ $dayIndex }}][{{ $field }}]" value="{{ old('operating_days.'.$dayIndex.'.'.$field,substr($schedule[$field] ?? '',0,5)) }}"></label>@endforeach</div><label class="w-100 mt-2">Evidence / source note<textarea class="form-control" name="operating_days[{{ $dayIndex }}][evidence_text]" rows="2">{{ old('operating_days.'.$dayIndex.'.evidence_text',$schedule['evidence_text'] ?? '') }}</textarea></label></div>
@endforeach</details>@endif
@forelse($review['graph']['stalls'] as $i=>$stall)
<article class="card market-card mb-4" data-stall-card><div class="card-body"><input type="hidden" name="stalls[{{ $i }}][selected]" value="0"><label class="ai-check"><input class="form-check-input" type="checkbox" name="stalls[{{ $i }}][selected]" value="1" @checked(old('stalls.'.$i.'.selected',$stall['selected'] ?? false)) data-select-stall> Include Stall</label>
<h3 class="h5">Stall {{ $i + 1 }}: {{ $stall['name'] ?: 'Name needs confirmation' }}</h3>
@if(empty($stall['name']))<p class="alert alert-warning small"><strong>Unverified food observed at this Market.</strong> Supply or link a source-supported Stall identity before any Foods in this group can be imported.</p>@endif
@if($stall['missing'])<p class="text-danger small">Missing: {{ implode(' · ', $stall['missing']) }}</p>@endif
@if(!empty($stall['needs_repair']) || empty($stall['name']))<button type="submit" class="btn btn-sm btn-outline-danger mb-2" formaction="{{ route('admin.ai-import.remove-invalid',$proposal) }}" name="repair_item" value="stall:{{ $i }}">Remove this invalid Stall group</button>@endif
<label class="form-label w-100">Stall name<input class="form-control" name="stalls[{{ $i }}][name]" value="{{ old('stalls.'.$i.'.name',$stall['name']) }}"></label>
<label class="form-label w-100">Link existing Stall<select name="stalls[{{ $i }}][matched_stall_id]" class="form-select" data-existing-stall><option value="">Create new inactive Stall</option>@foreach($review['existingStalls'] as $existing)<option value="{{ $existing->id }}" @selected(old('stalls.'.$i.'.matched_stall_id',$stall['matched_stall_id'])==$existing->id)>{{ $existing->name }} · {{ ucfirst($existing->status) }}</option>@endforeach</select></label>
@if($stall['duplicates'])<p class="alert alert-warning small">Possible existing Stall. Link the matching record above or skip this duplicate.</p>@endif
<p class="small ai-evidence">{{ $stall['evidence_text'] ?? 'No ownership evidence provided.' }}</p><input type="hidden" name="stalls[{{ $i }}][parent_confirmed]" value="0"><label class="ai-check"><input class="form-check-input" type="checkbox" name="stalls[{{ $i }}][parent_confirmed]" value="1" @checked(old('stalls.'.$i.'.parent_confirmed',$stall['parent_confirmed'] ?? false))> I confirmed this Stall belongs to the selected Market.</label><p class="small">Halal stays Unknown without qualifying evidence.</p>
@foreach($stall['foods'] as $j=>$food)
@include('admin.ai-import._food', ['i'=>$i,'j'=>$j,'food'=>$food,'stall'=>$stall])
@endforeach</div></article>
@empty<div class="alert alert-info">No Stalls or Foods have been extracted yet. You can review and import the selected new inactive Market on its own, or analyse another source for more details. An unreadable source can be supplemented with text or screenshots.</div>@endforelse
@if(($review['duplicateMarkets'] ?? collect())->isNotEmpty() || ($review['duplicateDrafts'] ?? collect())->isNotEmpty())<div class="alert alert-warning"><strong>Possible duplicate Night Market.</strong> Link the existing record above or continue the unfinished draft by default. The backend blocks another matching Market unless you explicitly confirm a separate record.@foreach($review['duplicateMarkets'] as $duplicate)<div>Existing Market: <a href="{{ route('admin.night-markets.show',$duplicate) }}">{{ $duplicate->name }} · {{ $duplicate->city }} · {{ ucfirst($duplicate->status) }}</a></div>@endforeach @foreach($review['duplicateDrafts'] as $duplicate)<div>Unfinished: <a href="{{ route('admin.ai-import.show',$duplicate) }}">Draft #{{ $duplicate->id }}</a></div>@endforeach<label class="ai-check mt-2"><input type="hidden" name="allow_duplicate_market" value="0"><input type="checkbox" class="form-check-input" name="allow_duplicate_market" value="1"> I verified this is a genuinely separate Night Market and still want another record.</label></div>@endif
<label class="ai-check" id="review-confirmation"><input class="form-check-input" type="checkbox" name="confirm" value="1" @checked(old('confirm')) aria-describedby="review-confirmation-help" @if($errors->has('confirm')) aria-invalid="true" @endif> I reviewed Market ownership, source evidence and the selected records. Create new records as inactive.</label>
<p class="small" id="review-confirmation-help">Required only when creating records. Save and continue later does not require confirmation.</p>
@error('confirm')<p class="text-danger" role="alert"><a href="#review-confirmation">{{ $message }}</a></p>@enderror
@php($selectedStalls = collect($review['graph']['stalls'])->where('selected',true))
@php($selectedFoods = $selectedStalls->sum(fn($stall) => collect($stall['foods'] ?? [])->where('selected',true)->count()))
<div class="ai-selection-bar"><span data-selection-count>{{ count($review['sources']) }} sources · {{ $selectedStalls->count() }} stalls · {{ $selectedFoods }} foods</span><button class="btn btn-market" type="submit" name="action" value="import" data-import-label>{{ $review['context']['market_id'] || !empty($review['graph']['market']['matched_night_market_id']) ? 'Add Selected Records' : ($selectedStalls->isEmpty() ? 'Create 1 Night Market' : 'Create Selected Catalog Records') }}</button><button class="btn btn-outline-secondary" type="submit" name="action" value="save" formnovalidate>Save and continue later</button><span role="status" data-busy-status></span></div><p class="small">Saving preserves an editable draft. Import creates only selected records as inactive after this review confirmation.</p></form></section></div>
@if($review['canDeleteEmpty'])<details class="mt-4"><summary>Remove unused empty draft</summary><p>This removes only this unused working proposal. Source history and catalog records are not deleted.</p><form method="POST" action="{{ route('admin.ai-import.destroy-empty',$proposal) }}">@csrf @method('DELETE')<label class="ai-check"><input type="checkbox" required> I want to remove this unused empty draft.</label><button class="btn btn-outline-danger">Remove empty draft</button></form></details>@endif
@endif</div>@endsection
