@extends('layouts.app')
@section('title', 'Review catalog draft | NightBite')
@section('content')<div class="ai-import">
@include('admin.ai-import._header', ['heading' => 'Build your catalog draft', 'stage' => $proposal->status === 'imported' ? 3 : 1])
@if($proposal->status === 'imported')
<div class="alert alert-success">Imported. Refreshing this page does not import again. New records remain inactive until normal Admin activation.</div>
<div class="d-flex flex-wrap gap-2">@foreach($review['import_result']['records'] as $record)<a class="btn btn-outline-market" href="{{ route(match($record['type']) { 'food'=>'admin.foods.show', 'market'=>'admin.night-markets.show', default=>'admin.stalls.show' },$record['id']) }}">{{ $record['name'] }}</a>@endforeach</div>
@else
<div class="ai-workspace"><aside class="ai-sources-panel">
<h2 class="h4">Selected sources</h2>
<form method="POST" action="{{ route('admin.ai-import.analyse',$proposal) }}" enctype="multipart/form-data" data-ai-busy="Reading selected content and extracting draft items…">@csrf
@foreach($review['sources'] as $i => $source)<article class="card mb-3"><div class="card-body"><label class="ai-check"><input type="checkbox" name="source_ids[]" value="{{ $i }}" class="form-check-input"> {{ $source['title'] }}</label><p class="small" role="status">{{ $source['status'] }}</p><a href="{{ $source['url'] }}" target="_blank" rel="noopener noreferrer">Open Source</a>
@if(!empty($source['thumbnail']))<img class="ai-source-image my-2" src="{{ $source['thumbnail'] }}" alt="Video cover (source preview only)" loading="lazy" referrerpolicy="no-referrer">@endif<p class="small text-secondary">{{ $source['publisher'] }} · {{ $source['published_at'] ?? 'Publication date unavailable' }}</p>@if(!empty($source['metadata_status']))<p class="small">{{ $source['metadata_status'] }}</p>@endif
@if(!empty($source['text']))<details class="mt-2"><summary>Read extracted evidence</summary><p class="ai-evidence">{{ $source['text'] }}</p></details>@endif</div></article>@endforeach
<label for="additional-url" class="form-label">Add another source URL</label><input type="url" name="url" id="additional-url" class="form-control mb-3" placeholder="https://…">
<details class="mb-3"><summary>Video segment (not the full video)</summary><p class="small mt-2" id="video-range-help">For video URLs, analyse one source and up to 180 seconds at a time. Default: the first 120 seconds, or the video end if earlier. Check the video length using Open Source. To analyse another segment, choose its range explicitly. Text and screenshots do not use this range.</p><div class="row g-2"><label class="col-sm-6" for="video-start">Start (seconds)<input id="video-start" name="video_start_seconds" type="number" min="0" max="43199" class="form-control" value="{{ old('video_start_seconds',0) }}" aria-describedby="video-range-help"></label><label class="col-sm-6" for="video-end">End (seconds)<input id="video-end" name="video_end_seconds" type="number" min="1" max="43200" class="form-control" value="{{ old('video_end_seconds',120) }}" aria-describedby="video-range-help"></label></div></details>
<details><summary>Provide text or screenshot instead</summary><label class="form-label mt-2" for="source-text">Text from the selected source</label><textarea class="form-control" id="source-text" name="text" rows="5" maxlength="30000"></textarea><label class="form-label mt-2" for="screenshot">Source screenshot (JPEG, PNG, WebP; 5 MB)</label><input class="form-control" type="file" name="screenshot" id="screenshot" accept="image/jpeg,image/png,image/webp"><p class="small">Select one source when supplying text/screenshots. A video timestamp is not an image file.</p></details>
<button type="submit" class="btn btn-market w-100 mt-3">Analyse Selected</button><p class="small mt-2" role="status" data-busy-status>Only selected sources are analysed. Existing edits are retained; additional variants require review.</p></form></aside>
<section class="min-w-0"><h2 class="h4">{{ $review['graph']['market']['name'] ?? 'Market details' }}</h2><p>Check ownership and evidence. Missing information can remain in a draft. Uncheck incomplete items to import other complete items.</p>
<form method="POST" action="{{ route('admin.ai-import.update',$proposal) }}" enctype="multipart/form-data" data-ai-busy="Saving draft…">@csrf @method('PATCH')<input type="hidden" name="revision" value="{{ $revision }}">
@if(!$review['context']['market_id'])<div class="card card-body mb-3"><h3 class="h5">Market identity</h3><input type="hidden" name="market[selected]" value="0"><label class="ai-check"><input type="checkbox" class="form-check-input" name="market[selected]" value="1" @checked(old('market.selected',$review['graph']['market']['selected'] ?? false))> Include this new Market even without Stalls or Foods</label>@foreach(['name'=>'Market name','address'=>'Address','city'=>'City'] as $key=>$label)<label class="form-label">{{ $label }}<input name="market[{{ $key }}]" class="form-control" value="{{ old('market.'.$key,$review['graph']['market'][$key] ?? '') }}"></label>@endforeach<label>Link an existing Market instead<select class="form-select" name="market[matched_night_market_id]"><option value="">Create a new inactive Market</option>@foreach($nightMarkets as $m)<option value="{{ $m->id }}" @selected(($review['graph']['market']['matched_night_market_id'] ?? null)==$m->id)>{{ $m->name }} · {{ $m->city }}</option>@endforeach</select></label><p class="small mt-2">Selangor only. New markets require source-supported operating days before import.</p></div>@endif
@if(!$review['context']['market_id'])
<details class="card card-body mb-3"><summary>Operating days & source evidence</summary><p class="small">Select only source-supported days. Leave unknown times blank in the draft; selected new markets need complete times before import.</p>
@foreach(\App\Models\MarketOperatingDay::DAYS as $dayIndex=>$day)
@php($schedule = collect($review['graph']['operating_days'])->firstWhere('day_of_week',$day))
<div class="border-bottom py-2"><input type="hidden" name="operating_days[{{ $dayIndex }}][day_of_week]" value="{{ $day }}"><input type="hidden" name="operating_days[{{ $dayIndex }}][selected]" value="0"><label class="ai-check"><input type="checkbox" class="form-check-input" name="operating_days[{{ $dayIndex }}][selected]" value="1" @checked(old('operating_days.'.$dayIndex.'.selected',(bool)$schedule))> {{ $day }}</label><div class="row g-2">@foreach(['opening_time'=>'Opens','closing_time'=>'Closes'] as $field=>$label)<label class="col-sm-6">{{ $label }}<input type="time" class="form-control" name="operating_days[{{ $dayIndex }}][{{ $field }}]" value="{{ old('operating_days.'.$dayIndex.'.'.$field,substr($schedule[$field] ?? '',0,5)) }}"></label>@endforeach</div><label class="w-100 mt-2">Evidence / source note<textarea class="form-control" name="operating_days[{{ $dayIndex }}][evidence_text]" rows="2">{{ old('operating_days.'.$dayIndex.'.evidence_text',$schedule['evidence_text'] ?? '') }}</textarea></label></div>
@endforeach</details>@endif
@forelse($review['graph']['stalls'] as $i=>$stall)
<article class="card market-card mb-4" data-stall-card><div class="card-body"><input type="hidden" name="stalls[{{ $i }}][selected]" value="0"><label class="ai-check"><input class="form-check-input" type="checkbox" name="stalls[{{ $i }}][selected]" value="1" @checked(old('stalls.'.$i.'.selected',$stall['selected'] ?? false)) data-select-stall> Include Stall</label>
<label class="form-label w-100">Stall name<input class="form-control" name="stalls[{{ $i }}][name]" value="{{ old('stalls.'.$i.'.name',$stall['name']) }}"></label>
<label class="form-label w-100">Link existing Stall<select name="stalls[{{ $i }}][matched_stall_id]" class="form-select" data-existing-stall><option value="">Create new inactive Stall</option>@foreach($review['existingStalls'] as $existing)<option value="{{ $existing->id }}" @selected(old('stalls.'.$i.'.matched_stall_id',$stall['matched_stall_id'])==$existing->id)>{{ $existing->name }} · {{ ucfirst($existing->status) }}</option>@endforeach</select></label>
@if($stall['duplicates'])<p class="alert alert-warning small">Possible existing Stall. Link the matching record above or skip this duplicate.</p>@endif
<p class="small ai-evidence">{{ $stall['evidence_text'] ?? 'No ownership evidence provided.' }}</p><input type="hidden" name="stalls[{{ $i }}][parent_confirmed]" value="0"><label class="ai-check"><input class="form-check-input" type="checkbox" name="stalls[{{ $i }}][parent_confirmed]" value="1" @checked(old('stalls.'.$i.'.parent_confirmed',$stall['parent_confirmed'] ?? false))> I confirmed this Stall belongs to the selected Market.</label><p class="small">Halal stays Unknown without qualifying evidence.</p>
@foreach($stall['foods'] as $j=>$food)
@include('admin.ai-import._food', ['i'=>$i,'j'=>$j,'food'=>$food,'stall'=>$stall])
@endforeach</div></article>
@empty<div class="alert alert-info">No extracted items yet. Select a source and choose Analyse Selected. An unreadable source can be supplemented with text or screenshots.</div>@endforelse
<div class="ai-selection-bar"><span data-selection-count>Selections saved in this draft</span><button class="btn btn-market">Save Draft & Selections</button><a class="btn btn-outline-market" href="{{ route('admin.ai-import.review',$proposal) }}" data-review-link>Review Import</a><span role="status" data-busy-status></span></div><p class="small">Save edits before opening Review Import.</p></form></section></div>
@endif</div>@endsection
