@extends('layouts.app')
@section('title', 'Catalog drafts and import history | NightBite')
@section('content')
<div class="ai-import">
@include('admin.ai-import._header', ['heading' => 'Drafts & Import History', 'stage' => 0])
<nav class="d-flex flex-wrap gap-2 mb-4" aria-label="Saved work views">
@foreach(['active'=>'Active Drafts','attention'=>'Needs Attention','imported'=>'Imported History','archived'=>'Archived'] as $value=>$label)<a class="btn {{ ($filters['status'] ?? 'active') === $value ? 'btn-market' : 'btn-outline-secondary' }}" @if(($filters['status'] ?? 'active') === $value) aria-current="page" @endif href="{{ route('admin.ai-import.history',['status'=>$value]) }}">{{ $label }}</a>@endforeach
</nav>
<form method="GET" action="{{ route('admin.ai-import.history') }}" class="card market-card card-body mb-4"><input type="hidden" name="status" value="{{ $filters['status'] ?? 'active' }}"><div class="row g-3 align-items-end">
<label class="col-lg-5">Draft ID or Market name<input class="form-control" name="draft_search" value="{{ $filters['draft_search'] ?? '' }}" placeholder="e.g. 49 or Taman Garing Utama"></label>
<label class="col-lg-2">Import type<select class="form-select" name="draft_type"><option value="">All types</option><option value="new_market" @selected(($filters['draft_type'] ?? '') === 'new_market')>Create New</option><option value="existing" @selected(($filters['draft_type'] ?? '') === 'existing')>Add to Existing</option></select></label>
<label class="col-lg-2">Condition<select class="form-select" name="draft_condition"><option value="">All</option><option value="ready" @selected(($filters['draft_condition'] ?? '') === 'ready')>Ready</option><option value="incomplete" @selected(($filters['draft_condition'] ?? '') === 'incomplete')>Incomplete</option><option value="failed" @selected(($filters['draft_condition'] ?? '') === 'failed')>Failed</option></select></label>
<label class="col-lg-2">Last updated<select class="form-select" name="draft_sort"><option value="updated_desc" @selected(($filters['draft_sort'] ?? 'updated_desc') === 'updated_desc')>Newest first</option><option value="updated_asc" @selected(($filters['draft_sort'] ?? '') === 'updated_asc')>Oldest first</option></select></label>
<div class="col-lg-1 d-flex gap-2"><button class="btn btn-market">Apply</button><a class="btn btn-outline-secondary" href="{{ route('admin.ai-import.history',['status'=>$filters['status'] ?? 'active']) }}">Reset</a></div>
</div></form>
<div class="ai-source-grid">@forelse($proposals as $proposal)<article class="card market-card"><div class="card-body d-flex flex-column gap-2">
<div class="d-flex flex-wrap justify-content-between gap-2"><strong>Draft #{{ $proposal->id }}</strong><span class="badge {{ in_array($proposal->draft_display_status,['Analysis Failed','Missing Information']) ? 'text-bg-warning' : ($proposal->draft_display_status === 'Imported' ? 'text-bg-success' : 'text-bg-secondary') }}">{{ $proposal->draft_display_status }}</span></div>
<h2 class="h5 mb-0">{{ $proposal->draft_name ?: $proposal->draft_market_name }}</h2><p class="mb-0">{{ $proposal->draft_market_name }} @if($proposal->draft_market_city) · {{ $proposal->draft_market_city }} @endif</p>
<p class="small text-secondary mb-0">{{ $proposal->target_type === 'new_market' ? 'Create New' : 'Add to Existing' }} · Last updated {{ $proposal->updated_at->format('d M Y, H:i') }}</p><p class="small mb-0">{{ $proposal->draft_source_count }} Sources · {{ $proposal->draft_stall_count }} Stalls · {{ $proposal->draft_food_count }} Foods</p>
@if($proposal->draft_missing)<p class="small text-warning-emphasis mb-0"><strong>Needs attention:</strong> {{ implode(' · ',$proposal->draft_missing) }}</p>@endif
@if(($proposal->duplicate_draft_count ?? 0)>1)<p class="alert alert-warning small mb-0">{{ $proposal->duplicate_draft_count }} unfinished drafts appear to reference this Market. Continue the newest relevant draft instead of importing duplicates.</p>@endif
<div class="d-flex flex-wrap gap-2 mt-auto pt-2"><a class="btn btn-outline-market" href="{{ route($proposal->status === 'imported' ? 'admin.ai-import.success' : 'admin.ai-import.show',$proposal) }}">{{ $proposal->status === 'imported' ? 'View Imported Records' : 'Continue Review' }}</a>
@if($proposal->status === 'draft')<a class="btn btn-outline-secondary" href="{{ route('admin.ai-import.show',$proposal) }}#draft-sources">View Sources</a><details><summary class="btn btn-outline-secondary">Manage</summary><div class="border rounded p-3 mt-2"><form method="POST" action="{{ route('admin.ai-import.rename',$proposal) }}" class="mb-2">@csrf @method('PATCH')<label class="form-label">Draft name<input class="form-control" name="draft_name" maxlength="255" value="{{ $proposal->draft_name ?: $proposal->draft_market_name }}" required></label><button class="btn btn-sm btn-market">Rename</button></form><form method="POST" action="{{ route('admin.ai-import.archive',$proposal) }}" class="mb-2">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-secondary">Archive</button></form><form method="POST" action="{{ route('admin.ai-import.destroy',$proposal) }}" onsubmit="return confirm('Delete Draft #{{ $proposal->id }}? Catalog records and source history will not be deleted.');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></details>@endif
</div></div></article>@empty<div class="alert alert-info">No saved work matches this view. Search for sources to start a new draft.</div>@endforelse</div><div class="mt-4">{{ $proposals->links() }}</div></div>
@endsection
