@extends('layouts.app')
@section('title', 'Review Import | NightBite')
@section('content')<div class="ai-import">
@include('admin.ai-import._header', ['heading' => 'Review Import', 'stage' => 2])
<div class="alert alert-info">Only selected items below will be imported. New records are inactive and hidden from public browsing. Linked records will not be overwritten. No extra approval step is required.</div>
<h2 class="h4">{{ $review['marketName'] }} · {{ $review['marketCity'] }}, Selangor</h2>
<p>{{ $review['context']['market_id'] || !empty($review['graph']['market']['matched_night_market_id']) ? 'Link existing Market' : 'Create new inactive Market (address and operating days required)' }}</p>
<p class="fw-semibold">{{ collect($review['graph']['stalls'])->where('selected',true)->count() }} selected Stalls · {{ collect($review['graph']['stalls'])->where('selected',true)->flatMap(fn($s)=>$s['foods'])->where('selected',true)->count() }} selected Foods</p>
@foreach($review['graph']['stalls'] as $i=>$stall)@if(!empty($stall['selected']))<article class="card market-card mb-3"><div class="card-body"><h3 class="h5">{{ $stall['matched_stall_id'] ? 'Link' : 'Create' }} Stall: {{ $stall['name'] }}</h3>@if($stall['missing'])<p class="text-danger">{{ implode(' · ',$stall['missing']) }}</p>@endif
<div class="ai-source-grid">@foreach($stall['foods'] as $j=>$food)@if(!empty($food['selected']))<section class="card card-body">@if(!empty($food['image_path']))<img class="ai-food-photo" src="{{ route('admin.ai-import.image',[$proposal,$i,$j]) }}" alt="{{ $food['name'] }}">@endif<h4 class="h6 mt-2">{{ !empty($food['matched_food_id']) ? 'Link existing Food' : 'Create Food' }}: {{ $food['name'] }}</h4><p>{{ $food['category'] ?: 'Category missing' }} · {{ isset($food['price_min'],$food['price_max']) ? 'RM'.$food['price_min'].'–RM'.$food['price_max'] : 'Price missing' }}</p>@if($food['missing'] && empty($food['matched_food_id']))<p class="text-danger small">{{ implode(' · ',$food['missing']) }}</p>@endif</section>@endif @endforeach</div></div></article>@endif @endforeach
<form action="{{ route('admin.ai-import.import',$proposal) }}" method="POST" data-ai-busy="Importing selected records…">@csrf<input type="hidden" name="revision" value="{{ $revision }}"><label class="ai-check"><input class="form-check-input" type="checkbox" name="confirm" value="1" required> I reviewed ownership, prices, image permissions and selected records.</label><div class="d-flex flex-wrap gap-2 mt-3"><a class="btn btn-outline-secondary" href="{{ route('admin.ai-import.show',$proposal) }}">Back to Draft</a><button class="btn btn-market">Import Selected</button></div><p role="status" data-busy-status>Refresh never repeats analysis or import. Missing items can be deselected in the draft.</p></form></div>@endsection
