@extends('layouts.app')

@section('title', 'Manage Foods | Night Market Selangor')

@section('content')
    <div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h2 fw-bold mb-1">Foods</h1><p class="text-secondary mb-0">Manage food assignments, categories, and public availability.</p></div><a href="{{ route('admin.foods.create') }}" class="btn btn-market align-self-start">Create Food</a></div>
    <div class="card market-card mb-4"><div class="card-body p-4"><form method="GET" action="{{ route('admin.foods.index') }}" class="row g-3 align-items-end">
        <div class="col-12 col-lg-4"><label for="search" class="form-label">Food name or description</label><input id="search" name="search" type="search" value="{{ $filters['search'] ?? '' }}" class="form-control @error('search') is-invalid @enderror">@error('search')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label for="night_market_id" class="form-label">Night Market</label><select id="night_market_id" name="night_market_id" class="form-select @error('night_market_id') is-invalid @enderror"><option value="">All markets</option>@foreach ($nightMarkets as $nightMarket)<option value="{{ $nightMarket->id }}" @selected((string) ($filters['night_market_id'] ?? '') === (string) $nightMarket->id)>{{ $nightMarket->name }}</option>@endforeach</select>@error('night_market_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label for="stall_id" class="form-label">Stall</label><select id="stall_id" name="stall_id" class="form-select @error('stall_id') is-invalid @enderror"><option value="">All stalls</option>@foreach ($stalls as $stall)<option value="{{ $stall->id }}" @selected((string) ($filters['stall_id'] ?? '') === (string) $stall->id)>{{ $stall->name }}</option>@endforeach</select>@error('stall_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label for="category" class="form-label">Category</label><select id="category" name="category" class="form-select @error('category') is-invalid @enderror"><option value="">All categories</option>@foreach ($categories as $category)<option value="{{ $category->category }}" @selected(($filters['category'] ?? '') === $category->category)>{{ $category->category }}</option>@endforeach</select>@error('category')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label for="is_must_try" class="form-label">Must-try</label><select id="is_must_try" name="is_must_try" class="form-select @error('is_must_try') is-invalid @enderror"><option value="">All</option><option value="1" @selected(($filters['is_must_try'] ?? '') === '1')>Yes</option><option value="0" @selected(($filters['is_must_try'] ?? '') === '0')>No</option></select>@error('is_must_try')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-6 col-lg-2"><label for="status" class="form-label">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 col-lg-3 d-flex gap-2"><button class="btn btn-market" type="submit">Apply</button><a class="btn btn-outline-secondary" href="{{ route('admin.foods.index') }}">Reset Filters</a></div>
    </form></div></div>
    @if ($foods->isEmpty())<div class="alert alert-info">No foods match the current filters.</div>@else
        <div class="card market-card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Food</th><th>Stall</th><th>Night Market</th><th>Category</th><th>Must-Try</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
            @foreach ($foods as $food)<tr><td><strong>{{ $food->name }}</strong></td><td>{{ $food->stall->name }}</td><td>{{ $food->stall->nightMarket->name }}</td><td>{{ $food->category ?: '—' }}</td><td>{{ $food->is_must_try ? 'Yes' : 'No' }}</td><td><span class="badge {{ $food->status === 'active' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ ucfirst($food->status) }}</span></td><td><div class="d-flex justify-content-end flex-wrap gap-2"><a href="{{ route('admin.foods.show', $food) }}" class="btn btn-sm btn-outline-secondary">View</a><a href="{{ route('admin.foods.edit', $food) }}" class="btn btn-sm btn-outline-primary">Edit</a><form method="POST" action="{{ $food->status === 'active' ? route('admin.foods.deactivate', $food) : route('admin.foods.activate', $food) }}" onsubmit="return confirm('{{ $food->status === 'active' ? 'Deactivate this food?' : 'Activate this food?' }}');">@csrf @method('PATCH')<button class="btn btn-sm {{ $food->status === 'active' ? 'btn-outline-danger' : 'btn-outline-success' }}" type="submit">{{ $food->status === 'active' ? 'Deactivate' : 'Activate' }}</button></form></div></td></tr>@endforeach
        </tbody></table></div></div>
        @if ($foods->hasPages())<nav class="d-flex justify-content-between align-items-center mt-4" aria-label="Food pagination"><a class="btn btn-outline-secondary {{ $foods->onFirstPage() ? 'disabled' : '' }}" href="{{ $foods->previousPageUrl() ?: '#' }}">Previous</a><span class="text-secondary">Page {{ $foods->currentPage() }} of {{ $foods->lastPage() }}</span><a class="btn btn-outline-secondary {{ $foods->hasMorePages() ? '' : 'disabled' }}" href="{{ $foods->nextPageUrl() ?: '#' }}">Next</a></nav>@endif
    @endif
@endsection
